name: C/C++ CI
on: [push, pull_request]
jobs:
  cmake:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
         os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Build
      uses: lukka/run-cmake@v0
    - name: Test
      uses: lukka/run-cmake@v0
      with:
        buildWithCMakeArgs: '--target test'
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
        QT_QPA_PLATFORM: offscreen
        QT_PLUGIN_PATH: ${{env.Qt5_Dir}}/plugins
