name: C/C++ CI
on: [push, pull_request]
jobs:
  job-qmake:
    name: QMake
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
         os: [ubuntu-latest, macos-latest, windows-latest]
         include: 
          - os: ubuntu-latest
            make: make
          - os: macos-latest
            make: make
          - os: windows-latest
            make: nmake
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Setup environment
      uses: ilammy/msvc-dev-cmd@v1
    - name: Configure
      run: qmake
    - name: Make
      run: ${{matrix.make}}
    - name: Test
      run: ${{matrix.make}} check TESTARGS="--platform offscreen"
  job-cmake:
    name: CMake
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
         os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Setup environment
      uses: ilammy/msvc-dev-cmd@v1
    - name: Setup more environment 
      if: runner.os == 'Windows'
      run: |
        echo "::set-env name=CC::cl.exe"
        echo "::set-env name=CXX::cl.exe"
    - name: Build
      uses: lukka/run-cmake@v0
    - name: Test
      uses: lukka/run-cmake@v0
      with:
        buildWithCMakeArgs: '--target test'
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
        QT_QPA_PLATFORM: offscreen
        QT_PLUGIN_PATH: ${{env.Qt5_Dir}}/plugins
