name: C/C++ CI
on: [push, pull_request]
jobs:
  qmake:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
         os: [ubuntu-latest, macos-latest, windows-latest]
         include: 
          - os: ubuntu-latest
            make: make
          - os: macos-latest
            make: make
          - os: windows-latest
            make: nmake
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: qmake
      run: qmake
    - name: make
      run: ${{matrix.make}}
    - name: make check
      run: ${{matrix.make}} check TESTARGS="--platform offscreen"
  cmake:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
         os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - if: runner.os == 'Windows'
      env:
        CC: cl
        CXX: cl
      run: echo noop
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
    - name: Build
      uses: lukka/run-cmake@v0
    - name: Test
      uses: lukka/run-cmake@v0
      with:
        buildWithCMakeArgs: '--target test'
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
        QT_QPA_PLATFORM: offscreen
        QT_PLUGIN_PATH: ${{env.Qt5_Dir}}/plugins
      
